### ISSUE TITLE
Green stripes randomly show when play videos.

### ISSUE THREAD

**Issue by fisherguy** [linux-sunxi/libvdpau-sunxi#40]
I compiled and install on Allwinner H3 based OrangePi PC, it works with mpv but artifacts like green stripes will show randomly on played videos. Any fix?

**Comment by jemk** [comment]
First, it looks like you are using software decoding.

When software decoding is used there was a missing cache flush, it is fixed with 6174e3406f07b364424a9ea2c3ed0f7befd25dc2 on master.

**Comment by fisherguy** [comment]
@jemk Green stripes still shows. Check below link for screenshot.
http://postimg.org/image/yrnc5majj/

**Comment by fisherguy** [comment]
Here is what I did today.
wget https://codeload.github.com/linux-sunxi/libvdpau-sunxi/zip/h3-dev
cd libvdpau-sunxi-h3-dev
make
sudo make install
sudo ln -s /usr/lib/arm-linux-gnueabihf/vdpau/libvdpau_sunxi.so.1 /usr/lib/libvdpau_nvidia.so
export VDPAU_DRIVER=sunxi

**Comment by jemk** [comment]
The h3-dev branch is old, I should delete it. Use the master branch.

**Comment by fisherguy** [comment]
@jemk Thank you very much. Problem solved.
